title: Zenseact Open Dataset

name: Zenseact

url: zenseact.github.io
baseurl: /

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "zenseact_beige"

include:
  - _data
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true

logo: "/assets/images/logo.png"

footer:
  links:
    - label: "Zenseact"
      icon: "fas fa-fw fa-building"
      url: "https://zenseact.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zenseact"

atom_feed:
  hide: true
